name: Test
on: workflow_dispatch
jobs:
  print:
    runs-on: windows-latest
    steps:
      - name: Print to console
        run: echo Hello Ations!
      - name: Print another line
        run: |
          echo Hello 1
          echo Hello 2
